# Ativa lints adicionais que ajudam a manter um código limpo e bem estruturado
warn(clippy::all)
warn(clippy::pedantic)
warn(clippy::nursery)

# Desativa lints que podem ser muito restritivos ou não aplicáveis
allow(clippy::module_name_repetitions)
allow(clippy::missing_errors_doc)
allow(clippy::missing_panics_doc)

# Configurações específicas para reforçar princípios SOLID
warn(clippy::too_many_arguments)
warn(clippy::large_enum_variant)
warn(clippy::type_complexity)
warn(clippy::cognitive_complexity)
